### ISSUE TITLE
补充鹏博士AS号

### ISSUE THREAD

**Issue by deddey** [gaoyifan/china-operator-ip#15]
补充鹏博士AS号：
AS19430 原长城宽带AS号，现改为北京息壤，鹏博士子公司
AS9395 国信比林，鹏博士孙公司
对其中部分IP段在ipip中抽样查询，部分仅由本自治域广播，多数部分同时由电信or联通or科技网等网络自治域广播。
很赞同“从技术角度来说，按照实际网络路由做划分也更加合理”这句。
在DNS分域解析中，如果我是鹏博士宽带接入用户，就算返回IP也由电信或联通广播，但如果是本AS域内地址段，连接走域内路由一般也应更快。
在多出口路由器应用中，若正好有鹏博士接入线路，又希望充分利用其带宽，可以把该段路由表优先执行，反之若希望优先走电信or联通，可以把该段路由表放最后执行。
以上，无论地址段是否单独由鹏博士所有自治域广播，加入鹏博士段均符合实际网络应用需求。（这也适用于其他网络接入商）
故望采纳加入，谢谢

**Comment by gaoyifan** [comment]
感谢您的报告！
AS9396 匹配规则已更新。下一次更新时将使用新的AS列表。

**Comment by gaoyifan** [comment]
[AS19430](https://bgp.he.net/AS19430#_prefixes) 是一个美国的自治域，且仅有 Level 3 一个上游。宣告的 4 段 IP 均在美国，看起来不像是一家国内的运营商。请再次确认一下。

* 139.61.78.0/23
* 139.61.86.0/23
* 139.61.112.0/21
* 198.160.124.0/24

**Comment by deddey** [comment]
晕，我打错了，不是19430，是17430

**Comment by deddey** [comment]
> 感谢您的报告！
> AS9396 匹配规则已更新。下一次更新时将使用新的AS列表。

这个应该是9395

**Comment by gaoyifan** [comment]
感谢您的报告！
AS9395, AS17430 匹配规则已更新。下一次更新时将使用新的AS列表。
