### ISSUE TITLE
【严重故障】21 日的自动网段信息更新提交异常，导致几乎所有文件都被清空

### ISSUE THREAD

**Issue by IceCodeNew** [gaoyifan/china-operator-ip#17]
如题，异常提交为 https://github.com/gaoyifan/china-operator-ip/commit/b97491ccdedcdf3a07e92f8f2b345872bae49288

表现为 `17 additions and 8,323 deletions`，这个提交下来几乎所有文件都被清空了。

**Comment by IceCodeNew** [comment]
问题已于次日消失，但可以的话还是想知道原因

**Comment by gaoyifan** [comment]
之前改了多线程模型，错误码没能正确处理
CI 从上游下载BGP数据时出错，生成了空的结果
https://travis-ci.org/github/gaoyifan/china-operator-ip/builds/700493279
https://github.com/gaoyifan/china-operator-ip/commit/a497a9fc471de411aab17e51f6ebc0ad9c768e1f

**Comment by gaoyifan** [comment]
fixed in 6f99765
