### ISSUE TITLE
ip-lists分支不更新了吗

### ISSUE THREAD

**Issue by CalmLong** [gaoyifan/china-operator-ip#19]
如题

**Comment by SeaHOH** [comment]
旧的 travis-ci.org 在逐步移除功能，可能定时任务已经失效，需要迁移到 .com 。

**Comment by gaoyifan** [comment]
感谢反馈！ 项目大约在6个月前已经迁移至了 travis-ci.com 
但奇怪的是，尽管设置了 Cron Job，但实际上 Crob Job 并未触发，我也没收到任何提醒邮件（大约在2个月前就没再执行了）

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/5450996/128495013-f4c7dfa1-14dc-48f4-9754-b779bf4de853.png">
<img width="331" alt="image" src="https://user-images.githubusercontent.com/5450996/128495069-75a9cccf-4f45-4928-add7-2213cc3ed46e.png">

**Comment by SeaHOH** [comment]
可能是服务运维出差错了，估计重新添加可以恢复正常。

**Comment by gaoyifan** [comment]
重设了定时任务，明天观察一下效果。如果还是不行，我来尝试迁移到 GitHub Actions

**Comment by SeaHOH** [comment]
今天更新发现我的也无法构建，然后到处找原因，终于点到 requests 页面才看见错误信息 "Could not authorize build request for */*"。stackoverflow 上说是没订阅，WTF!? 还要自己选 free plan?? 现在正常了。。。

**Comment by gaoyifan** [comment]
free plan credits 并非每月刷新，需要邮件申请 OSS Credits 配额。 考虑到 Travis-CI 免费策略逐渐收紧，预计会在近期迁移到 GitHub Actions

**Comment by gaoyifan** [comment]
已经迁移至 GitHub Actions 。每日 2:45 将自动更新预生成结果

**Comment by ChanthMiao** [comment]
> 已经迁移至 GitHub Actions 。每日 2:45 将自动更新预生成结果

你好，大约3个月前我基于这个项目做了两个简化版，移除了运营商分类:
- [ChanthMiao/China-IPv4-List](https://github.com/ChanthMiao/China-IPv4-List)
- [ChanthMiao/China-IPv6-List](https://github.com/ChanthMiao/China-IPv6-List)

使用GitHub Actions进行每日构建，仍然采用MIT协议。
