### ISSUE TITLE
加入 电信通/长城宽带/鹏博士 的IP地址数据

### ISSUE THREAD

**Issue by mzji** [gaoyifan/china-operator-ip#2]
~~根据淘宝IP数据库统计信息，~~ 电信通已具有约~~一千万~~260万IP地址，规模很大。建议将其IP地址信息作为独立运营商加入IP地址库。谢谢。

目前已知的电信通AS仅有
```
AS17964       DXTNET Beijing Dian-Xin-Tong Network Technologies Co., Ltd., CN
```
一个。

**Comment by gaoyifan** [comment]
之前曾有人通过其他渠道提出过这个建议，也简单调研了一下：

我抽查了一小部分鹏博士、电信通这类二级运营商的IP地址，发现有一些IP并非由这些运营商自己对外做广播，实际由电信、联通这些一级运营商代为广播。 如果将这些运营商单独列出来，可能会让大家误会电信通的IP地址只有这一点。 从技术角度来说，按照实际网络路由做划分也更加合理，如鹏博士的地址由联通代为广播，那么无论是DNS分域解析还是多出口路由器，认为这个IP就是联通线路也未尝不可。

不过，这只是初步的结论。如果能整理出一个完整的电信通ASN列表，那么完全可以对电信通进行独立统计。

**Comment by gaoyifan** [comment]
这是AS17964的IP：

```
1.93.1.0/24
1.94.0.0/16
14.196.0.0/16
14.197.144.0/22
14.197.160.0/20
27.106.204.0/22
42.197.0.0/16
42.199.0.0/18
42.199.132.0/24
49.221.0.0/19
60.194.0.0/15
60.206.0.0/15
101.44.0.0/14
101.104.0.0/17
101.106.192.0/19
101.106.224.0/20
101.106.240.0/21
101.107.64.0/18
101.126.60.0/22
101.246.192.0/18
103.23.56.0/22
115.33.0.0/16
115.34.0.0/15
115.47.28.0/24
115.120.128.0/17
115.173.64.0/18
116.218.128.0/18
116.242.0.0/16
118.145.128.0/17
118.196.0.0/15
118.205.0.0/16
118.206.0.0/20
118.206.16.0/22
118.207.128.0/17
118.244.125.0/24
118.244.129.0/24
118.244.130.0/24
121.68.0.0/16
121.71.0.0/16
123.196.112.0/20
123.197.128.0/17
124.14.128.0/19
124.15.64.0/18
124.192.0.0/15
124.200.0.0/16
124.202.0.0/17
124.203.128.0/22
124.204.0.0/16
124.206.0.0/15
175.188.192.0/19
180.86.4.0/24
180.86.156.0/24
180.88.0.0/18
180.88.192.0/18
180.91.0.0/17
180.91.160.0/19
202.14.235.0/24
202.14.236.0/23
202.14.238.0/24
202.38.152.0/23
202.91.128.0/22
202.99.1.0/24
202.99.63.0/24
202.130.0.0/19
203.158.16.0/24
203.158.19.0/24
203.158.23.0/24
203.207.64.0/19
203.207.112.0/20
203.207.128.0/18
203.207.192.0/21
203.207.208.0/20
203.207.224.0/19
210.75.96.0/19
210.76.96.0/19
211.100.224.0/19
211.101.32.0/19
211.147.0.0/19
211.155.128.0/19
211.155.240.0/20
211.161.16.0/22
211.161.28.0/22
211.162.48.0/20
211.162.108.0/22
211.162.128.0/18
211.162.208.0/20
211.167.224.0/19
218.241.242.0/24
218.244.224.0/19
218.247.0.0/19
218.247.128.0/17
218.249.0.0/16
219.234.128.0/17
219.238.0.0/15
220.112.128.0/18
220.114.16.0/20
220.114.204.0/22
220.114.208.0/20
220.114.224.0/21
220.114.252.0/22
220.115.64.0/18
220.115.144.0/22
220.115.160.0/19
220.115.192.0/19
220.115.224.0/22
223.208.0.0/17
223.210.52.0/22
223.210.56.0/21
223.210.64.0/19
223.210.224.0/19
223.211.224.0/19
```

共计2678784个IP，与一千万差异甚大

**Comment by mzji** [comment]
由于目前电信通、鹏博士、长城宽带内部网络割接合并已经结束，故目前以上三家企业的网络已合并为一张主干网。为方便起见，以下简称其为电信通。
根据目前所有的信息，我在一楼提到的这个AS确实为电信通骨干网所有，其中的prefix经确认并不含有一级运营商的IP地址。此AS大约含有IPv4地址 2,679,808 个（bgp.he.net数据）。
电信通的复杂度在于，根据bgp.he.net的互联图，电信通AS与联通、电信和CNNIC有互联，但与移动、铁通无互联。从技术角度上讲，电信通可视为一个小型的一级运营商。所以若不将其作为一个独立的运营商处理，则电信通的路由将全部由默认路由承担，可能会不太方便。在此我建议，将一楼我提到的AS中包含的IPv4地址作为目前电信通所拥有的*全部*IP地址，而其他由电信或联通负责路由的IP地址则作为电信或联通的IP地址。

**Comment by mzji** [comment]
又，歌华、方正、华数等地区运营商所拥有的IP地址群规模极小，且网络仅仅与在地单一网络运营商接入，故将其IP地址群视为联通/电信/移动的一部分较妥。

**Comment by gaoyifan** [comment]
90877a6 已加入，先观察一段时间吧。

**Comment by mzji** [comment]
非常感谢！

**Comment by mzji** [comment]
增补说明：电信通 AS 已与中移铁通互联，已与中国科技网断开互联

**Comment by deddey** [comment]
补充鹏博士AS号：
AS19430  原长城宽带AS号，现改为北京息壤，鹏博士子公司
AS9395  国信比林，鹏博士孙公司
对其中部分IP段在ipip中抽样查询，部分仅由本自治域广播，多数部分同时由电信or联通or科技网等网络自治域广播。
很赞同“从技术角度来说，按照实际网络路由做划分也更加合理”这句。
在DNS分域解析中，如果我是鹏博士宽带接入用户，就算返回IP也由电信或联通广播，但如果是本AS域内地址段，连接走域内路由一般也应更快。
在多出口路由器应用中，若正好有鹏博士接入线路，又希望充分利用其带宽，可以把该段路由表优先执行，反之若希望优先走电信or联通，可以把该段路由表放最后执行。
以上，无论地址段是否单独由鹏博士所有自治域广播，加入鹏博士段均符合实际网络应用需求。（这也适用于其他网络接入商）
故望采纳加入，谢谢
