### ISSUE TITLE
麻烦问下如何采集不同国家的ip

### ISSUE THREAD

**Issue by ttsite** [gaoyifan/china-operator-ip#23]
有没有类似的工具或者软件可以准 确采集除中国以外其它国家地区的ip或者ip段的. 不用国内的纯真ip的情况下。或者有没有这方面工具.谢谢!

**Comment by gaoyifan** [comment]
您可以参考中国的配置，添加其他国家的配置，然后执行 `./generate.sh` 生成对应国家的数据：
https://github.com/gaoyifan/china-operator-ip/blob/master/operator/china.conf

更准确的方案是对 ASN 做标注，配合路径追踪数据标注出全网的地理位置。但这需要投入相当多的精力。

如果对准确性有较高的要求，建议使用商业数据库。自己从零维护一个高质量IP库的成本会显著高于购买数据。

**Comment by ttsite** [comment]
谢谢

**Comment by stuacct073** [comment]
如果只是精确到IP所在的国家，那么工作量还好，这个(https://bgp.he.net/AS24131)就可以确定asn对应的国家，接下来就是遍历IP，解析BGP数据了
