### ISSUE TITLE
没有包含 AS24424

### ISSUE THREAD

**Issue by MonwF** [gaoyifan/china-operator-ip#3]
是有意的吗？

**Comment by gaoyifan** [comment]
并非有意的，之前没有注意到这个AS。
刚查了一下，这似乎是Google在中国的AS。是希望直接将其划分给某家运营商（如电信）吗？

**Comment by MonwF** [comment]
划到电信可以的。。。移动这个段ping高很多

**Comment by gaoyifan** [comment]
我这样想的，目前的表仍然保持不变（即：都是运营商自有的AS），开个新坑：整理一份与一级运营商直接相连的AS。
比如：某IDC与电信、联通直接相连，则这些IP同时记录到电信、联通两个数据库中。如Google CN仅与电信相连，则这些IP都添加到电信的库中。 这么做可能更适合路由器，用户只需要手动配置路由优先级即可。

**Comment by MonwF** [comment]
这样也可以

我路由器里的用法：国内非移动ip走电信，剩余的都是移动宽带。这样相加漏掉的ip会fallback到移动宽带，导致不能访问。

我看china.txt里有这些ip段，准备修改为移动ip走移动宽带，china.txt里的走电信，但得手动清除移动ip的冗余。不知道有没更好方案？

**Comment by gaoyifan** [comment]
路由可以配置优先级，不需要清除冗余的IP。 
```
cmcc.txt走移动  优先级最高
china.txt走电信  优先级较低
```

这样一来，移动地址已经被优先匹配了，即便china.txt中也存在移动IP，也不会选择电信出口。

**Comment by MonwF** [comment]
我知道，只是查找效率会低点，有点强迫症

Yifan Gao <notifications@github.com>于2017年4月11日 周二18:44写道：

**Comment by gaoyifan** [comment]
[cidrmerge](http://cidrmerge.sourceforge.net)可以做IP集合减法（china.txt-cmcc.txt)

**Comment by MonwF** [comment]
好的，谢谢了，我回去优化下。可以关了

Yifan Gao <notifications@github.com>于2017年4月11日 周二20:30写道：
