### ISSUE TITLE
数据采集的原理是什么

### ISSUE THREAD

**Issue by wthahaha** [gaoyifan/china-operator-ip#36]
大佬，这个项目是如何从边界网关采集到这些数据的，能分享下思路或原理吗

**Comment by gaoyifan** [comment]
有公开的数据源 https://archive.routeviews.org/

**Comment by ArcCal** [comment]
大佬，能提供个自动更新的txt给clash用不

**Comment by gaoyifan** [comment]
这超出了本项目的目标。如果需要类似的自动数据源，可以参考[这个项目](https://github.com/Loyalsoldier/clash-rules?tab=readme-ov-file)，借助 GitHub Action ，实现自动化生成。
