### ISSUE TITLE
信息纠错

### ISSUE THREAD

**Issue by deseuwing** [gaoyifan/china-operator-ip#40]
2a13:df85:be80::/48 是美国加利福尼亚州洛杉矶网络

**Comment by gaoyifan** [comment]
看起来这是一个注册在中国的小型个人自治域。从维护者填写的描述来看，似乎（未来）[可能会在中国宣告](https://bgp.he.net/AS216342#_prefixes6)。

由于目前的规则集仅支持整体性排除整个ASN的地址，如果你能联络 [JIANYU SHAO](https://bgp.he.net/AS216342) 的管理员，可否确认一下未来是否有在国内的宣告计划。

目前我将先排除整个 AS216342。如果有更新，可随时重新开启本 issue。
