### ISSUE TITLE
增加ipv6的記錄

### ISSUE THREAD

**Issue by yangzhaofeng** [gaoyifan/china-operator-ip#7]
目前 ipip.net 已經支持ipv6的查詢，你是不是也考慮一下增加ipv6的路由記錄呢

**Comment by 1265578519** [comment]
ipv6现在实际中没有应用无所谓了

**Comment by yangzhaofeng** [comment]
@1265578519 教育網有ipv6，三大運營商也正在部署，目前手機4g信號已經可以訪問ipv6的資源了

**Comment by yangzhaofeng** [comment]
https://github.com/ustclug/auth-dns/pull/4

**Comment by yangzhaofeng** [comment]
ustclug/auth-dns#4

**Comment by yangzhaofeng** [comment]
#12
